services:
  db:
    image: postgres
    container_name: db
    restart: always #container reinicia se morrer
    ports:
      - 5433:5432
    env_file:
      - .env #configurar POSTGRES_USER, POSTGRES_PASSWORD e POSTGRES_DB
    volumes:
      - pg:/var/lib/postgresql/data # onde os dados do postgres ficam armazenados no sistema operacional

  node_app:
    container_name: node_app
    build: . #Dockerfile do node se encontra na pasta atual
    ports:
      - 5000:5000
    depends_on:
      - db # sรณ sobe quando o postgres tiver no ar
    env_file:
      - .env #configurar DATABASE_URL

volumes:
  pg: # volume para os postgres
